# Generated by Django 5.1.7 on 2025-03-15 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_remove_answer_answers_answer_options_answer_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='options',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='statement',
            new_name='stem',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
        migrations.AddField(
            model_name='answer',
            name='option_text',
            field=models.TextField(default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_options', to='question.question'),
        ),
    ]
