# Generated by Django 5.1.7 on 2025-11-18 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_alter_question_theme_alter_theme_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='year',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='question.edition'),
        ),
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='question.theme'),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
