# Generated by Django 5.1.7 on 2025-12-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_alter_exam_description_alter_exam_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='examextractiontask',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='examextractiontask',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
