# Generated by Django 5.1.7 on 2025-12-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_examextractiontask_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edition',
            name='year',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
