# Generated by Django 5.1.7 on 2026-02-26 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_alter_edition_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examextractiontask',
            name='answer_key_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/ai_keys/'),
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/question_images/')),
                ('filename', models.CharField(max_length=255)),
                ('mime_type', models.CharField(default='image/jpeg', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='question.question')),
            ],
        ),
    ]
