# Generated by Django 5.1.7 on 2026-02-26 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_alter_examextractiontask_answer_key_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='question',
            name='theme',
        ),
        migrations.AddField(
            model_name='exam',
            name='name_base',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='exam',
            name='name_sigle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='style',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='total_questions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='variant',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='exam',
            name='year',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='question',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.JSONField(default=list, help_text="[{'label': 'A', 'text': 'Option A text'}, ...]"),
        ),
        migrations.AddField(
            model_name='question',
            name='question_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
        migrations.DeleteModel(
            name='Edition',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
