# Generated by Django 5.1.7 on 2026-03-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_remove_question_edition_remove_question_theme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='description',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='title',
        ),
    ]
