# Generated by Django 5.1.7 on 2026-03-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0018_remove_exam_description_remove_exam_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sources',
            field=models.JSONField(default=list, help_text="['Source 1', 'Source 2']"),
        ),
    ]
