# Generated by Django 5.1.7 on 2026-09-17 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0019_question_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_questions',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='has_image',
            field=models.BooleanField(blank=True),
        ),
    ]
