# Generated by Django 5.1.7 on 2026-09-23 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_alter_exam_total_questions_alter_question_has_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='total_questions',
        ),
    ]
