services:
  backend:
    container_name: django_site_questoes
    user: duser
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./dotenv_files/.env
