[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django==5.1.7",
    "djangorestframework==3.16.0",
    "djangorestframework-simplejwt>=5.5.1",
    "django-cors-headers==4.7.0",
    "python-dotenv==1.0.1",
    "pillow>=12.0.0",
    "requests>=2.32.0",
    "rich>=14.2.0",
    "drf-spectacular>=0.29.0",
    "python-magic>=0.4.27",
    "pydantic>=2.13.1",
    "mypy>=2.3.1",
]

[dependency-groups]
dev = [
  "mypy>=1.13",
  "django-stubs>=6.1.1",
  "djangorestframework-stubs>=3.18.1",
  "pytest>=9.1.1",
  "pytest-django>=4.14.0",
  "pytest-dotenv>=0.5.2",
  "ruff>=0.16.4",
]

[tool.ruff]
line-length = 79
target-version = "py313"
fix = true
show-fixes = true
indent-width = 4
exclude = [
  ".venv",
  "*/migrations/*.py",
]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "T201",   # Checks for print statements,
  "COM812", # Checks for the absence of trailing commas.
  "INP001", # Checks for packages that are missing an __init__.py file.
  "D",      # All pydocstyle (D)
  "ANN401", # Checks that function arguments are annotated with a more specific type than Any.
  "ERA001", # Checks for commented-out Python code.
  "A004",   # Shadowing Python Builtin
  "ARG001", # Unused function arguments
  "CPY001",
  "DJ001",
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "ANN001",
    "ANN002",
    "ANN003",
    "ANN201",
    "PLR2004",
    "S101",
    "S105",
    "S106",
    "SLF001",
]
"**/tests*.py" = [
    "ANN001",
    "ANN002",
    "ANN003",
    "ANN201",
    "ANN202",
    "PLR2004",
    "S101",
    "S105",
    "S106",
    "SLF001",
    "PLC0415",
    "EM101",
    "TRY003"
]
"*/migrations/*.py" = ["ALL"]
"project/settings.py" = [
    "E501", # Ignore line-length violations for long secret keys or database URLs
]
"manage.py" = ["ALL"]
"**/views.py" = ["ARG002"]
"__init__.py" = ["F401"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

[tool.ruff.lint.isort]
known-first-party = ["backend", "project", "user", "question"]

[tool.pyright]
typeCheckingMode = "standard"
pythonVersion = "3.14"
include = ["apps"]
exclude = [
  "**/venv",
  "**/.venv",
  "**/env",
  "**/.env",
  "**/node_modules",
  "**/__pycache__",
  "*/migrations/*",
]
venv = ".venv"
venvPath = "."
executionEnvironments = [{ root = "." }]
reportIncompatibleVariableOverride = "none"

[tool.mypy]
python_version = "3.14"
plugins = ["mypy_django_plugin.main"]
exclude = ["migrations/"]
ignore_missing_imports = true
check_untyped_defs = true

[tool.django-stubs]
django_settings_module = "project.settings"

[tool.pytest.ini_options]
addopts = "-s --color=yes --tb=short"
testpaths = ["apps/tests"]
DJANGO_SETTINGS_MODULE = "project.settings"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
