# Generated by Django 5.1.7 on 2025-03-14 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_answer_correct_alter_question_correct_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='correct',
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='question.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=1),
        ),
    ]
