# Generated by Django 5.1.7 on 2025-03-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_remove_answer_correct_answer_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answers',
        ),
        migrations.AddField(
            model_name='answer',
            name='options',
            field=models.CharField(default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='answer',
            name='text',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
