# Generated by Django 5.1.7 on 2025-06-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_files_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/<django.db.models.fields.related.ForeignKey>/files'),
        ),
    ]
