# Generated by Django 5.1.7 on 2025-03-30 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='bot_message',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user_message',
            field=models.CharField(max_length=2000),
        ),
    ]
