# Generated by Django 5.1.7 on 2025-03-16 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_alter_question_options_rename_options_answer_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='option',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='answer',
            name='option_text',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(default='Não está atriubída à nenhum tema.', on_delete=django.db.models.deletion.SET_DEFAULT, to='question.theme'),
        ),
        migrations.AddField(
            model_name='question',
            name='edition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='question.edition'),
        ),
    ]
