# Generated by Django 5.1.7 on 2025-06-18 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_edition_alter_answer_option_alter_answer_option_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='theme',
            field=models.ForeignKey(default='Sem tema', on_delete=django.db.models.deletion.SET_DEFAULT, to='question.theme'),
        ),
    ]
