const questions = [
  {
    id: 1,
    title: "Question 1",
    description: "Description for question 1",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 2,
    title: "Question 2",
    description: "Description for question 2",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 3,
    title: "Question 3",
    description: "Description for question 3",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 4,
    title: "Question 4",
    description: "Description for question 4",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 5,
    title: "Question 5",
    description: "Description for question 5",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 6,
    title: "Question 6",
    description: "Description for question 6",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 7,
    title: "Question 7",
    description: "Description for question 7",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 8,
    title: "Question 8",
    description: "Description for question 8",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 9,
    title: "Question 9",
    description: "Description for question 9",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 10,
    title: "Question 10",
    description: "Description for question 10",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 11,
    title: "Question 11",
    description: "Description for question 11",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 12,
    title: "Question 12",
    description: "Description for question 12",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 13,
    title: "Question 13",
    description: "Description for question 13",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 14,
    title: "Question 14",
    description: "Description for question 14",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 15,
    title: "Question 15",
    description: "Description for question 15",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 16,
    title: "Question 16",
    description: "Description for question 16",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 17,
    title: "Question 17",
    description: "Description for question 17",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 18,
    title: "Question 18",
    description: "Description for question 18",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 19,
    title: "Question 19",
    description: "Description for question 19",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 20,
    title: "Question 20",
    description: "Description for question 20",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 21,
    title: "Question 21",
    description: "Description for question 21",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 22,
    title: "Question 22",
    description: "Description for question 22",
    options: ["a", "b", "c", "d", "e"],
  },
  {
    id: 23,
    title: "Question 23",
    description: "Description for question 23",
    options: ["a", "b", "c", "d", "e"],
  },
];

export default questions;
