# Generated by Django 5.1.7 on 2025-11-18 17:00

import apps.user.models
import apps.user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.user.models.CustomUserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='file',
            name='file_type',
            field=models.CharField(blank=True, choices=[('csv', 'CSV File'), ('pdf', 'PDF File')], max_length=50),
        ),
        migrations.AddField(
            model_name='file',
            name='file_upload',
            field=models.FileField(null=True, upload_to='files', validators=[apps.user.validators.validate_file_type]),
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
